### ISSUE TITLE
Support for tags/labels

### ISSUE THREAD

**Issue by kanishkarj** [layer5io/service-mesh-performance-specification#22]
Support of tags or labels for SMPS can turn out very useful. An very obvious and mostly the most important advantage is the ease of indexing and searching through the reports. Also considering the fact that large organizations might have stored 100s of 1000s of performance test results stored, something like tags or labels will help speed up the search by great magnitudes.

The question remains which would be better, tags or labels.

Tags : 
```yaml
tags: 
- v1
- prod
- project-xyz
- wrk2
```

Labels:
```yaml
labels: 
- version: 1
- env: prod
- app: project-xyz
- tool: wrk2
```

In my opinion labels seem more powerful.
